# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = ACGDreamLoadPlugs
DESTDIR = ../.build/vs/ACGDreamLoadPlugs/lib
CONFIG += staticlib debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(ACGDreamLoadPlugs.pri)
