# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = ACGDreamFrame
DESTDIR = ../.build/vs/ACGDreamFrame/lib
CONFIG += staticlib debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(ACGDreamFrame.pri)
