# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./common/Components/Components.h \
    ./buildLib/config/config.h \
    ./common/GUI/UIBuild/uic/ui_GUIMain.h \
    ./common/GUI/UIBuild/uic/ui_testW.h \
    ./include/ACGDreamFrameH.h \
    ./common/Animation/API/AnimationAPI.h \
    ./common/Components/PushButton/PushButtonStyle1.h \
    ./common/GUI/GUIMain/GUIMain.h \
    ./common/Animation/MoveAnimation/MoveAnimation.h \
    ./common/Animation/Animation.h \
    ./main/ACGDreamFrame.h \
    ./common/Components/ScrollArea/ScrollAreaStyle1.h
SOURCES += ./common/Animation/API/AnimationAPI.cpp \
    ./main/ACGDreamFrame.cpp \
    ./common/Animation/Animation.cpp \
    ./common/Components/PushButton/PushButtonStyle1.cpp \
    ./common/Components/ScrollArea/ScrollAreaStyle1.cpp \
    ./common/Animation/MoveAnimation/MoveAnimation.cpp \
    ./common/GUI/GUIMain/GUIMain.cpp
FORMS += ./common/GUI/GUIMain/GUIMain.ui
RESOURCES += ACGDreamFrame.qrc
