# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ACGDream
DESTDIR = ../.build/vs/ACGDream/lib
CONFIG += debug
LIBS += -L"./ACGDreamFrame.dll" \
    -L"./ACGDreamFrame.lib"
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(ACGDream.pri)
